### PR TITLE
feat: style download & useful links asides

### LINKED ISSUE #21: feat: style secondary blocks
The Rolex design system defines some secondary blocks styles:
Screenshot 2022-11-24 at 9 52 31 AM

Can be seen on http://rlxntr2022.ocitocine.com/pages/layouts/intranet/who.html for instance, or in the XD file under the "minisite" components (bottom center).

We have a few good candidates for this on our pages:
- /en/rolex-booth
- /en/evening-events
- /en/transfers
- /en/accreditations

The Download portal and Useful links blocks would make great examples. Also on the French pages.

I think there are 2 ways to achieve this:
1. Isolate the content in a dedicated section, and use a "Section Metadata" block to define a style property we can target in CSS. See https://www.hlx.live/developer/markup-sections-blocks#sections
2. Wrap the content in a dedicated block that will get it's custom styling

I'd be tempted to go with 1. as it makes authoring the content easier

### PR DESCRIPTION
**Pull request by solaris007**
Introduction of secondary component styles.

Fix #21 

Test URLs:
- Before: https://main--rolex-event--hlxsites.hlx.page/en/accomodation
- After:
  - https://issue-21--rolex-event--hlxsites.hlx.page/en/accomodation

### CODE REVIEW

**Comment by solaris007** [comment]
starting with Downloads & Useful Links asides:
Screenshot 2022-11-25 at 13 16 53
Screenshot 2022-11-25 at 13 16 34

Authoring:
Screenshot 2022-11-25 at 13 19 39

The style metadata "useful-links" and "downloads" are optional currently.

**Comment by solaris007** [comment]
PSI looking good (bot again weird):

Screenshot 2022-11-25 at 13 23 20

**Comment by ekremney** [comment]
I cannot see the `.aside` block in the "After" URL

**Review by ramboz — APPROVED** [review]
Looks good to me!

**Pull request merged**
